apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- credentials.yaml
- jenkins-volume.yaml
- jenkins.yaml
- jenkins-service.yaml
- jenkins-ingress.yaml

configMapGenerator:
- name: jenkins-plugins
  namespace: jenkins
  files:
  - config/plugins.txt
  disableNameSuffixHash: true
